version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${POST_USER}"
      POSTGRES_PASSWORD: "${POST_PASSWORD}"
      POSTGRES_DB: "${POST_DB}"
  crawler:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
